### ISSUE TITLE
Installation complete. code-oss launches blank windo

### ISSUE THREAD

**Issue by PhxCycler** [headmelted/codebuilds#64] opened 2018-11-21 21:20 UTC
I installed code-oss on raspbian running in a Virtualbox VM. The installation looks like it completed successfully. When I launch code-oss (either via terminal or via the Programming shortcut) I get a blank black window and nothing else. I don't see any error messages.

I've attached the installation log for this command: 
. <( wget -O - https://code.headmelted.com/installers/apt.sh )

I've tried installing a number of times and get the same situation every time. I've installed within Virtualbox/Raspbian on a different computer and it works there, so I'm assuming that something is missing here. Any thoughts on how to debug the issue?

Thank you,
-Mike

[code-oss_install-log.txt](https://github.com/headmelted/codebuilds/files/2605810/code-oss_install-log.txt)

**Comment by astupidmoose** [comment] 2018-12-31 00:43
Same issue for me on raspbian here as well. 

Tried using the packages and compiling from scratch and both have the same issue. 

Just a dark grey window.

**Comment by astupidmoose** [comment] 2018-12-31 00:54
Here is the full log of trying to run with code-oss --disable-gpu --verbose


> pi@raspberrypi:~ $ code-oss --disable-gpu --verbose
[20118:1231/005232.143212:WARNING:browser_main_loop.cc(275)] <unknown>: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
Error: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /usr/share/code-oss/resources/app/node_modules.asar.unpacked/spdlog/build/Release/spdlog.node)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:180:18)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at n (/usr/share/code-oss/resources/app/out/vs/loader.js:15:808)
    at bindings (/usr/share/code-oss/resources/app/node_modules.asar/bindings/bindings.js:81:44)
    at Object.<anonymous> (/usr/share/code-oss/resources/app/node_modules.asar/spdlog/index.js:3:35)
    at Object.<anonymous> (/usr/share/code-oss/resources/app/node_modules.asar/spdlog/index.js:21:3)
    at Module.o._compile (/usr/share/code-oss/resources/app/out/vs/loader.js:16:72)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Function.i [as __$__nodeRequire] (/usr/share/code-oss/resources/app/out/vs/loader.js:31:146)
    at Object.t.createSpdLogService (/usr/share/code-oss/resources/app/out/vs/code/electron-main/main.js:237:561)
    at /usr/share/code-oss/resources/app/out/vs/code/electron-main/main.js:500:639
    at Object.v [as _notify] (/usr/share/code-oss/resources/app/out/vs/code/electron-main/main.js:98:572)
    at Object.enter (/usr/share/code-oss/resources/app/out/vs/code/electron-main/main.js:101:924)
    at n.Class.derive._creator._run (/usr/share/code-oss/resources/app/out/vs/code/electron-main/main.js:103:790)
    at n.Class.derive._creator._completed (/usr/share/code-oss/resources/app/out/vs/code/electron-main/main.js:103:231)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Error: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/share/code-oss/resources/app/node_modules.asar.unpacked/native-keymap/build/Release/keymapping.node)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:180:18)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at n (/usr/share/code-oss/resources/app/out/vs/loader.js:15:808)
    at NativeBinding._init (/usr/share/code-oss/resources/app/node_modules.asar/native-keymap/index.js:15:22)
    at NativeBinding.onDidChangeKeyboardLayout (/usr/share/code-oss/resources/app/node_modules.asar/native-keymap/index.js:37:10)
    at Object.exports.onDidChangeKeyboardLayout (/usr/share/code-oss/resources/app/node_modules.asar/native-keymap/index.js:61:18)
    at e.onDidChangeKeyboardLayout (/usr/share/code-oss/resources/app/out/vs/code/electron-main/main.js:187:416)
    at t.registerListeners (/usr/share/code-oss/resources/app/out/vs/code/electron-main/main.js:486:429)
    at t (/usr/share/code-oss/resources/app/out/vs/code/electron-main/main.js:483:752)
    at t.create (/usr/share/code-oss/resources/app/out/vs/code/electron-main/main.js:65:770)
    at t.e._createInstance (/usr/share/code-oss/resources/app/out/vs/code/electron-main/main.js:217:215)
    at t.e.createInstance (/usr/share/code-oss/resources/app/out/vs/code/electron-main/main.js:216:561)
    at /usr/share/code-oss/resources/app/out/vs/code/electron-main/main.js:500:693
    at Object.v [as _notify] (/usr/share/code-oss/resources/app/out/vs/code/electron-main/main.js:98:572)
    at Object.enter (/usr/share/code-oss/resources/app/out/vs/code/electron-main/main.js:101:924)
    at n.Class.derive._creator._run (/usr/share/code-oss/resources/app/out/vs/code/electron-main/main.js:103:790)
    at n.Class.derive._creator._completed (/usr/share/code-oss/resources/app/out/vs/code/electron-main/main.js:103:231)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[main 00:52:34] Starting VS Code
[main 00:52:34] from: /usr/share/code-oss/resources/app
[main 00:52:34] args: { _: [],
  help: false,
  h: false,
  version: false,
  v: false,
  wait: false,
  w: false,
  diff: false,
  d: false,
  add: false,
  a: false,
  goto: false,
  g: false,
  'new-window': false,
  n: false,
  'unity-launch': false,
  'reuse-window': false,
  r: false,
  'open-url': false,
  performance: false,
  p: false,
  'prof-startup': false,
  verbose: true,
  logExtensionHostCommunication: false,
  logStorage: false,
  'disable-extensions': false,
  disableExtensions: false,
  'list-extensions': false,
  'show-versions': false,
  nolazy: false,
  issue: false,
  'skip-getting-started': false,
  'skip-release-notes': false,
  'sticky-quickopen': false,
  'disable-restore-windows': false,
  'disable-telemetry': false,
  'disable-updates': false,
  'disable-crash-reporter': false,
  'skip-add-to-recently-opened': false,
  status: false,
  s: false,
  'file-write': false,
  'file-chmod': false,
  'driver-verbose': false,
  trace: false,
  'disable-gpu': true }
[main 00:52:34] Resolving machine identifier...
[main 00:52:34] Resolved machine identifier: a34e819ed010be2a6fa2cfb742b93ab597f18df095c359c4c19ef73c5fe2b848
xdg-settings: unknown desktop environment
[main 00:52:34] windowsManager#open
[main 00:52:35] update#ctor - updates are disabled
[20118:1231/005239.840924:INFO:CONSOLE(1442)] "Error: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /usr/share/code-oss/resources/app/node_modules.asar.unpacked/spdlog/build/Release/spdlog.node)", source: file:///usr/share/code-oss/resources/app/out/vs/workbench/workbench.main.js (1442)
[20118:1231/005239.841629:INFO:CONSOLE(1435)] "%cTRACE", source: file:///usr/share/code-oss/resources/app/out/vs/workbench/workbench.main.js (1435)
[20118:1231/005239.867301:INFO:CONSOLE(1435)] "%c INFO", source: file:///usr/share/code-oss/resources/app/out/vs/workbench/workbench.main.js (1435)
[20118:1231/005239.869133:INFO:CONSOLE(1435)] "%c INFO", source: file:///usr/share/code-oss/resources/app/out/vs/workbench/workbench.main.js (1435)
[20118:1231/005239.924456:INFO:CONSOLE(0)] "Uncaught (in promise) #<Object>", source: file:///usr/share/code-oss/resources/app/out/vs/code/electron-browser/workbench/workbench.html?config=%7B%22_%22%3A%5B%5D%2C%22verbose%22%3Atrue%2C%22disable-gpu%22%3Atrue%2C%22appRoot%22%3A%22%2Fusr%2Fshare%2Fcode-oss%2Fresources%2Fapp%22%2C%22machineId%22%3A%22a34e819ed010be2a6fa2cfb742b93ab597f18df095c359c4c19ef73c5fe2b848%22%2C%22nodeCachedDataDir%22%3A%22%2Fhome%2Fpi%2F.config%2FCode%20-%20OSS%20(headmelted)%2FCachedData%2Ff74c7914490b68b4052ff877f04b6eaf7198f261%22%2C%22mainPid%22%3A20118%2C%22execPath%22%3A%22%2Fusr%2Fshare%2Fcode-oss%2Fcode-oss%22%2C%22userEnv%22%3A%7B%22VSCODE_IPC_HOOK%22%3A%22%2Frun%2Fuser%2F1000%2Fvscode-4ecaae40-1.29.0-main.sock%22%2C%22VSCODE_NLS_CONFIG%22%3A%22%7B%5C%22locale%5C%22%3A%5C%22en-gb%5C%22%2C%5C%22availableLanguages%5C%22%3A%7B%7D%2C%5C%22_languagePackSupport%5C%22%3Atrue%7D%22%2C%22VSCODE_LOGS%22%3A%22%2Fhome%2Fpi%2F.config%2FCode%20-%20OSS%20(headmelted)%2Flogs%2F20181231T005234%22%7D%2C%22isInitialStartup%22%3Atrue%2C%22backupPath%22%3A%22%2Fhome%2Fpi%2F.config%2FCode%20-%20OSS%20(headmelted)%2FBackups%2F1546199385523%22%2C%22windowId%22%3A1%2C%22logLevel%22%3A0%2C%22perfEntries%22%3A%5B%22mark%22%2C%22main%3Astarted%22%2C1546217553214%2C0%2C0%2C%22mark%22%2C%22main%3AappReady%22%2C1546217553485%2C0%2C1%2C%22mark%22%2C%22nlsGeneration%3Astart%22%2C1546217553493%2C0%2C2%2C%22mark%22%2C%22nlsGeneration%3Aend%22%2C1546217553495%2C0%2C3%2C%22mark%22%2C%22main%3AloadWindow%22%2C1546217555433%2C0%2C0%5D%7D (0)
[20118:1231/005239.925460:INFO:CONSOLE(0)] "Uncaught (in promise) #<Object>", source: file:///usr/share/code-oss/resources/app/out/vs/code/electron-browser/workbench/workbench.html?config=%7B%22_%22%3A%5B%5D%2C%22verbose%22%3Atrue%2C%22disable-gpu%22%3Atrue%2C%22appRoot%22%3A%22%2Fusr%2Fshare%2Fcode-oss%2Fresources%2Fapp%22%2C%22machineId%22%3A%22a34e819ed010be2a6fa2cfb742b93ab597f18df095c359c4c19ef73c5fe2b848%22%2C%22nodeCachedDataDir%22%3A%22%2Fhome%2Fpi%2F.config%2FCode%20-%20OSS%20(headmelted)%2FCachedData%2Ff74c7914490b68b4052ff877f04b6eaf7198f261%22%2C%22mainPid%22%3A20118%2C%22execPath%22%3A%22%2Fusr%2Fshare%2Fcode-oss%2Fcode-oss%22%2C%22userEnv%22%3A%7B%22VSCODE_IPC_HOOK%22%3A%22%2Frun%2Fuser%2F1000%2Fvscode-4ecaae40-1.29.0-main.sock%22%2C%22VSCODE_NLS_CONFIG%22%3A%22%7B%5C%22locale%5C%22%3A%5C%22en-gb%5C%22%2C%5C%22availableLanguages%5C%22%3A%7B%7D%2C%5C%22_languagePackSupport%5C%22%3Atrue%7D%22%2C%22VSCODE_LOGS%22%3A%22%2Fhome%2Fpi%2F.config%2FCode%20-%20OSS%20(headmelted)%2Flogs%2F20181231T005234%22%7D%2C%22isInitialStartup%22%3Atrue%2C%22backupPath%22%3A%22%2Fhome%2Fpi%2F.config%2FCode%20-%20OSS%20(headmelted)%2FBackups%2F1546199385523%22%2C%22windowId%22%3A1%2C%22logLevel%22%3A0%2C%22perfEntries%22%3A%5B%22mark%22%2C%22main%3Astarted%22%2C1546217553214%2C0%2C0%2C%22mark%22%2C%22main%3AappReady%22%2C1546217553485%2C0%2C1%2C%22mark%22%2C%22nlsGeneration%3Astart%22%2C1546217553493%2C0%2C2%2C%22mark%22%2C%22nlsGeneration%3Aend%22%2C1546217553495%2C0%2C3%2C%22mark%22%2C%22main%3AloadWindow%22%2C1546217555433%2C0%2C0%5D%7D (0)
[20118:1231/005240.481337:INFO:CONSOLE(181)] "Error: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /usr/share/code-oss/resources/app/node_modules.asar.unpacked/spdlog/build/Release/spdlog.node)", source: file:///usr/share/code-oss/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js (181)
[20118:1231/005240.497435:INFO:CONSOLE(181)] "Error: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /usr/share/code-oss/resources/app/node_modules.asar.unpacked/spdlog/build/Release/spdlog.node)", source: file:///usr/share/code-oss/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js (181)

**Comment by Noxiss11** [comment] 2019-02-24 13:58
I also faced the same issue on my PI.
Guys, any suggestions?

**Comment by DJenner8** [comment] 2019-02-25 04:32
I upgraded to "code-oss_1.32.0-1550644722_armhf.deb" using Synaptic Package Manager on my Raspberry Pi 3B+ running latest Raspbian.

When I start Code-OSS I get a completely black window with only the menu bar showing.  Nothing in the menu works.  I need to kill processes to quit Code-OSS.

The previous version worked just fine.

**Comment by marcowy** [comment] 2019-02-25 12:44
Same here - blank screen, no menu.
I've installed code-oss for the first time, followed the instruction from https://pimylifeup.com/raspberry-pi-visual-studio-code/

curl -L https://code.headmelted.com/installers/apt.sh | sudo bash


[main 2019-02-25T12:36:47.524Z] windowsManager#open
ATTENTION: default value of option force_s3tc_enable overridden by environment.
[1075:0225/133647.651535:ERROR:sandbox_linux.cc(379)] InitializeSandbox() called with multiple threads in process gpu-process.
[1039:0225/133648.260307:ERROR:gpu_process_transport_factory.cc(1017)] Lost UI shared context.
[main 2019-02-25T12:36:48.420Z] [storage state.vscdb] open(/home/pi/.config/Code - OSS (headmelted)/User/globalStorage/state.vscdb, retryOnBusy: true)
[main 2019-02-25T12:36:48.511Z] [storage state.vscdb] open(): Unable to open DB due to [object Object]
[main 2019-02-25T12:36:48.535Z] [storage state.vscdb] open(): Unable to use backup due to Error: ENOENT: no such file or directory, unlink '/home/pi/.config/Code - OSS (headmelted)/User/globalStorage/state.vscdb'
[1092:0225/133648.558764:ERROR:command_buffer_proxy_impl.cc(133)] ContextResult::kTransientFailure: Failed to send GpuChannelMsg_CreateCommandBuffer.
[1039:0225/133653.009092:INFO:CONSOLE(1400)] "%cTRACE", source: file:///usr/share/code-oss/resources/app/out/vs/workbench/workbench.main.js (1400)
[1039:0225/133653.035240:INFO:CONSOLE(1400)] "%c  ERR", source: file:///usr/share/code-oss/resources/app/out/vs/workbench/workbench.main.js (1400)
[1039:0225/133653.050350:INFO:CONSOLE(1400)] "%c  ERR", source: file:///usr/share/code-oss/resources/app/out/vs/workbench/workbench.main.js (1400)

**Comment by Dixeran** [comment] 2019-02-27 15:52
For now, install a old version can [bypass this problem.](https://github.com/headmelted/codebuilds/issues/67#issuecomment-466255567)

**Comment by DJenner8** [comment] 2019-02-27 16:43
Exactly which file?

**Comment by Dixeran** [comment] 2019-02-28 00:37
> Exactly which file?
> […](#)
> On Feb 27, 2019, at 7:52 AM, Dixeran ***@***.***> wrote: For now, install a old version can bypass this problem. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

```
apt-get install code-oss=1.29.0-1539702286
```

**Comment by mcshaman** [comment] 2019-03-07 03:24
Same issue

**Comment by kwende** [comment] 2019-03-14 18:30
Any resolution besides installing old stuff?

**Comment by wsura** [comment] 2019-04-11 05:57
Same issue...

**Comment by giovanymoreno** [comment] 2019-05-04 17:52
Same.

**Comment by MrZeusTheCoder** [comment] 2019-05-08 23:36
Does anyone have a solution other than downgrading? Just updated to 1.33 on Manjaro Linux via `pacman`.

**Comment by SPK-RPI** [comment] 2019-05-31 03:02
the same problem anyone has a solution.

**Comment by opemipoVRB** [comment] 2019-06-13 13:49
To Remove The Failing Build
1) `sudo apt-get purge code-oss`

To install Downgrade
2) `sudo apt-get install code-oss=1.29.0-1539702286`

To prevent Downgrade from Updating Automatically
3)` sudo apt-mark hold code-oss`

TO Undo Step 3
4) ` sudo apt-mark unhold code-oss`

**Comment by quanxavier** [comment] 2019-06-13 15:24
@opemipoVRB Many thanks for the resolution!!! Now I can play around with it on my chromebook.
![Screenshot_20190613_112338](https://user-images.githubusercontent.com/4028007/59445466-b8d09400-8dcd-11e9-8323-18a7538004cb.png)

**Comment by AchmadFathoni** [comment] 2019-06-15 15:19
Same issue Ubuntu mate 18.04 on odroid XU4

**Comment by MercedesPagoda** [comment] 2019-06-17 04:13
I have a similar issue but not exactly same problem. 
I installed successfully code-oss under the Kali NetHunter environment in Nexus9. When I launch code-oss by a terminal or a program shortcut, nothing happens, say no windows open. Although I tried the latest version as well as the downgraded one, the  problem remains unchanged. I need your helps. Thank you.

**Comment by abdullah20401** [comment] 2019-06-24 01:16
Thanks bro
> To Remove The Failing Build
> 
> 1. `sudo apt-get purge code-oss`
> 
> To install Downgrade
> 2) `sudo apt-get install code-oss=1.29.0-1539702286`
> 
> To prevent Downgrade from Updating Automatically
> 3)` sudo apt-mark hold code-oss`
> 
> TO Undo Step 3
> 4) ` sudo apt-mark unhold code-oss`

**Comment by nockieboy** [comment] 2019-06-28 08:28
> To Remove The Failing Build
> 
> 1. `sudo apt-get purge code-oss`
> 
> To install Downgrade
> 2) `sudo apt-get install code-oss=1.29.0-1539702286`
> 
> To prevent Downgrade from Updating Automatically
> 3)` sudo apt-mark hold code-oss`
> 
> TO Undo Step 3
> 4) ` sudo apt-mark unhold code-oss`

Can confirm this works on Raspbian Buster (on a Raspberry Pi 4) as well.  Good advice, opemipoVRB!

**Comment by missalyss** [comment] 2019-06-30 01:01
I've tried downgrading, but still get a blank screen. I've tried deleting (did a `sudo rm -rf` in `usr/share/applications`. Maybe that didn't really uninstall it?) and reinstalling. Installed it, immediately put it to version 1.29, but same results. Can anyone help?

**Comment by besh27** [comment] 2019-07-02 16:27
Have the same issue in vscode running in raspbian. I will try the fix @opemipoVRB just posted later today. Thanks!

**Comment by besh27** [comment] 2019-07-02 16:43
@missalyss I assume the configuration files or archived files associated with vscode are still present. You can run ```sudo apt-get --purge remove <program-name>``` to remove the config files,  ```sudo apt-get purge --auto-remove <program-name>``` to remove associated packages, or just ```sudo apt-get clean <package-name>``` to do both at the same time. That may help you clean the previous vscode version for you.

**Comment by Mozillex** [comment] 2019-07-20 21:23
@opemipoVRB Thank you for this concise, perfect solution!

**Comment by opemipoVRB** [comment] 2019-07-22 17:11
You're welcome @Mozillex  @nockieboy @abdullah20401  @quanxavier

**Comment by AuniverseA** [comment] 2019-07-22 22:42
I tried downgrading but still the same and now it also crashes my RPI.
Using RPI 3 b+.

**Comment by opemipoVRB** [comment] 2019-07-23 22:12
@AuniverseA  did you try a purge? 

"sudo apt-get purge code-oss"

**Comment by Vifier-Lockla** [comment] 2019-07-26 15:15
I had the same thing on Raspberry PI 3 B+ : I soluced few minutes ago after those commands from terminal :

sudo apt-get update
...
sudo apt-get upgrade
...
code-oss
.... and surprise : it works !!! In fact libraries on my Raspberry PI weren't the last...

I will try to reinstall last version of code-oss just to valid this sentence : "Before install code-oss, assume you upgraded before the libraries (absolutely all) of your Raspberry PI !!!" ...

**Comment by Vifier-Lockla** [comment] 2019-08-03 12:27
### Fine ! It works on Raspberry Pi 4B (raspbian buster)

**Here is minimal command lines to be able to start on new Raspberry Pi 4B :**

### Installation on RPI 4B

1. Execute this first command on your terminal :
<pre>curl -s https://packagecloud.io/install/repositories/headmelted/codebuilds/script.deb.sh | sudo bash</pre>

2. Continue with this second command : 
<pre>curl -L https://code.headmelted.com/installers/apt.sh | sudo bash</pre>

### Change Code-OSS version

1.  To Remove the current version

    <pre>sudo apt-get purge code-oss</pre>

2. To install new version

    <pre>sudo apt-get install code-oss=1.29.0-1539702286</pre>

3. To prevent Downgrade from Updating Automatically

    <pre>sudo apt-mark hold code-oss</pre>

**Comment by kevinjs** [comment] 2019-09-25 15:24
> To Remove The Failing Build
> 
> 1. `sudo apt-get purge code-oss`
> 
> To install Downgrade
> 2) `sudo apt-get install code-oss=1.29.0-1539702286`
> 
> To prevent Downgrade from Updating Automatically
> 3)` sudo apt-mark hold code-oss`
> 
> TO Undo Step 3
> 4) ` sudo apt-mark unhold code-oss`

It works fine on Raspberry pi 4b(Raspbian Buster), thanks.

**Comment by brentwooddev** [comment] 2019-09-30 16:55
Installation on RPI 4
OS: "Raspbian GNU/Linux 10 (buster)"

Doesn't work:
sudo apt-get purge code-oss
sudo apt-get install code-oss=1.29.0-1539702286
Getting this error:
pi@raspberrypi:~ $ sudo apt-get install code-oss=1.29.0-1539702286
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package code-oss

Any help would be appreciated thx.

**Comment by markusrudolf** [comment] 2019-10-25 11:39
When is this supposed to be fixed in HEAD?

**Comment by billcestmoi** [comment] 2019-12-08 01:19
> 
> 
> To Remove The Failing Build
> 
>     1. `sudo apt-get purge code-oss`
> 
> 
> To install Downgrade
> 2) `sudo apt-get install code-oss=1.29.0-1539702286`
> 
> To prevent Downgrade from Updating Automatically
> 3)` sudo apt-mark hold code-oss`
> 
> TO Undo Step 3
> 4) ` sudo apt-mark unhold code-oss`

it works fine on Raspberry pi 3b,wonderful! thanks

**Comment by headmelted** [comment] 2019-12-12 14:16
This issue exists in a few tickets, I'm closing them down as I believe the issue is resolved (insofar as I've been able to re-create and rectify it in the latest build).

Please attempt to update to the latest version and re-open this issue if the problem persists.

**Closed by headmelted** 2019-12-12 14:16 UTC
